In [26]:
from sklearn.model_selection import train_test_split
import numpy as np

%load_ext lab_black

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black


In [33]:
# columns
X = np.arange(20)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
# target
y = np.concatenate((np.zeros((1, 10)), np.ones((1, 10))), axis=1)[0]
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
X_train, X_test, y_train, y_test

(array([ 0, 16, 19, 11, 15,  4,  5,  9,  2,  8,  7, 12, 10]),
 array([ 6,  1, 13, 17, 14, 18,  3]),
 array([0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1.]),
 array([0., 0., 1., 1., 1., 1., 0.]))

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42
)
X_train, X_test, y_train, y_test

(array([ 3, 18, 16, 13,  2,  9, 19,  4, 12,  7, 10, 14,  6]),
 array([ 0, 17, 15,  1,  8,  5, 11]),
 array([0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0.]),
 array([0., 1., 1., 0., 0., 0., 1.]))

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify=y)
X_train, X_test, y_train, y_test

(array([14,  4, 13, 16, 11, 17,  9, 10, 12,  0,  3,  7,  5]),
 array([ 2,  6, 15,  1,  8, 19, 18]),
 array([1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 1., 1.]))

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, stratify=y, random_state=42
)
X_train, X_test, y_train, y_test

(array([12, 16, 10,  9, 19, 11,  6, 18,  1,  5,  2, 15,  0]),
 array([ 8, 17,  7, 13, 14,  3,  4]),
 array([1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 1., 1., 0., 0.]))