In [3]:
from sklearn.model_selection import train_test_split
import numpy as np

%load_ext lab_black

In [4]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = np.concatenate((np.zeros((1, 5)), np.ones((1, 5))), axis=1)[0]
y

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)
X_train, X_test, y_train, y_test

(array([5, 8, 2, 4, 9, 6]),
 array([0, 1, 7, 3]),
 array([1., 1., 0., 0., 1., 1.]),
 array([0., 0., 1., 0.]))

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=42
)
X_train, X_test, y_train, y_test

(array([7, 2, 9, 4, 3, 6]),
 array([8, 1, 5, 0]),
 array([1., 0., 1., 0., 0., 1.]),
 array([1., 0., 1., 0.]))

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, stratify=y)
X_train, X_test, y_train, y_test

(array([4, 9, 0, 5, 3, 6]),
 array([7, 2, 8, 1]),
 array([0., 1., 0., 1., 0., 1.]),
 array([1., 0., 1., 0.]))

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, stratify=y, random_state=42
)
X_train, X_test, y_train, y_test

(array([8, 4, 1, 6, 7, 2]),
 array([0, 3, 5, 9]),
 array([1., 0., 0., 1., 1., 0.]),
 array([0., 0., 1., 1.]))